# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Research Hub
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  The University of Cambridge Museums Research Hub.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://research.museums.cam.ac.uk" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: camunivmuseums
github_username:  jekyll
lang: EN_GB
timezone: Europe/London
permalink: pretty
encoding: "utf-8"
read_time: true
# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-mentions

words_per_minute: 200

collections:
   news:
      output: true
   projects:
      output: true
   researchers:
      output: true
   ideas:
      output: true
   collections:
      output: true
   casestudies:
      output: true
feed:
  collections:
    - news
    - projects
    - researchers
    - ideas
    - collections
    - casestudies
    
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
